name: tk_pertiwi
description: "A new Flutter project."

# Mencegah publikasi ke pub.dev secara tidak sengaja.
publish_to: 'none'

# Versi aplikasi: formatnya adalah [major].[minor].[patch]+[build_number]
version: 1.0.0+1

# Versi SDK Dart yang didukung
environment:
  sdk: '>=3.4.0 <4.0.0'

# Dependensi utama
dependencies:
  flutter:
    sdk: flutter

  # Ikon bergaya iOS
  cupertino_icons: any

  # Manajemen state & routing
  get: ^4.6.6

  # Penyimpanan data lokal
  get_storage: ^2.1.1

  # Cache gambar dari jaringan
  cached_network_image: ^3.3.0

  # HTTP request
  http: ^0.13.6

  smooth_page_indicator: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter untuk memastikan praktik coding yang baik
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/fonts/
    - assets/img/style_font.png
    - assets/img/logo.png
    - assets/img/profile.png
    - assets/img/playground.png
    - assets/img/sc.png
    - assets/img/armor_titan.jpg
    - assets/img/attack_titan.jpg
    - assets/img/beast_titan.jpg
  fonts:
    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
      

